### ISSUE TITLE
about clang

### ISSUE THREAD

**Issue by arizaini** [ryan-andri/android_kernel_xiaomi_santoni#2]
sir ... about your old clang kernel [here](https://github.com/ryan-andri/android_kernel_santoni/tree/Clang/Oreo) ... can you tell me from where clang related commit started and which should i picked sir? i was looking around commit history but get confuse which the commit should i pick btw i'm planning with pie caf base kernel (3.18.120). thanks before sir

**Comment by ryan-andri** [comment]
> sir ... about your old clang kernel [here](https://github.com/ryan-andri/android_kernel_santoni/tree/Clang/Oreo) ... can you tell me from where clang related commit started and which should i picked sir? i was looking around commit history but get confuse which the commit should i pick btw i'm planning with pie caf base kernel (3.18.120). thanks before sir

i'm using nathanchance's clang patch that can be found in : https://github.com/nathanchance/android-kernel-clang

**Comment by arizaini** [comment]
apply partial commit or just merge by branch sir?

**Comment by magchuz** [comment]
meh sorry

**Comment by ryan-andri** [comment]
wkwkwkwk udah ah capek pakai english, pakai bahasa indonesia aja napa :v

**Comment by ryan-andri** [comment]
> 
> 
> meh sorry

itu nongol otomatis sbagai preference issue
